import { Chapel } from '../types';

export interface ReportData {
  chapel: Chapel;
  weekRange?: string;
  monthRange?: string;
  totalDonations: number;
  totalMembers: number;
  averageDonation: number;
  interpretation: string;
  executiveSummary?: string[];
  statisticalSummary?: string[];
  trendAnalysis?: string[];
  interpretationBullets?: string[];
  recommendations?: string[];
}

export function generateReportInterpretation(data: ReportData): string {
  const { totalDonations, totalMembers, averageDonation, chapel } = data;
  
  let interpretation = `${chapel.name} - Financial and Member Report\n\n`;
  
  if (totalDonations > 0) {
    interpretation += `Total Donations: ₱${totalDonations.toLocaleString('en-PH', { minimumFractionDigits: 2 })}\n`;
    interpretation += `Total Members: ${totalMembers}\n`;
    interpretation += `Average Donation per Member: ₱${averageDonation.toLocaleString('en-PH', { minimumFractionDigits: 2 })}\n\n`;

    if (averageDonation > 1000) {
      interpretation += `✓ Strong giving pattern. The average donation per member (₱${averageDonation.toFixed(0)}) indicates high engagement.\n`;
    } else if (averageDonation > 500) {
      interpretation += `✓ Good giving pattern. Moderate average donations suggest steady member support.\n`;
    } else {
      interpretation += `• Average donations are lower. Consider increasing member engagement and tithing awareness.\n`;
    }

    if (totalMembers > 100) {
      interpretation += `✓ Strong community. The chapel has a growing congregation.\n`;
    }

    const donationPerCapita = totalDonations / totalMembers;
    if (donationPerCapita > 2000) {
      interpretation += `✓ High financial health. Annual per-member giving exceeds ₱2,000.\n`;
    }
  } else {
    interpretation += `No donation records available for this period.\n`;
  }

  return interpretation;
}

export function exportToCSV(data: ReportData): string {
  const separator = '-------------------------------------------------------------';
  const now = new Date().toLocaleString('en-PH');
  
  let csv = separator + '\n';
  csv += '                         KALOOB\n';
  csv += '             DONATION SUMMARY REPORT\n';
  csv += separator + '\n\n';
  csv += data.chapel.name + '\n\n';
  csv += 'Generated:\n';
  csv += now + '\n\n';
  csv += separator + '\n';
  csv += '                  FINANCIAL OVERVIEW\n';
  csv += separator + '\n\n';
  csv += '+-------------------------------------------+\n';
  csv += `| Total Donations            ₱${data.totalDonations.toLocaleString('en-PH', { minimumFractionDigits: 2 }).padStart(14)} |\n`;
  csv += '+-------------------------------------------+\n\n';
  csv += '+-------------------------------------------+\n';
  csv += `| Registered Members               ${data.totalMembers.toString().padStart(6)} |\n`;
  csv += '+-------------------------------------------+\n\n';
  csv += '+-------------------------------------------+\n';
  csv += `| Average Donation             ₱${data.averageDonation.toLocaleString('en-PH', { minimumFractionDigits: 2 }).padStart(10)} |\n`;
  csv += '+-------------------------------------------+\n\n';
  csv += separator + '\n';
  csv += 'REPORT INTERPRETATION\n';
  csv += separator + '\n\n';
  
  const totalDonations = data.totalDonations;
  const totalMembers = data.totalMembers;
  const averageDonation = data.averageDonation;
  
  csv += `The parish collected a total donation of ₱${totalDonations.toLocaleString('en-PH', { minimumFractionDigits: 2 })} from\n`;
  csv += `${totalMembers} registered members.\n\n`;
  csv += `The average contribution per member is ₱${averageDonation.toLocaleString('en-PH', { minimumFractionDigits: 2 })},\n`;
  csv += 'demonstrating healthy participation from parishioners.\n\n';
  csv += 'Overall Status:\n';
  
  if (averageDonation >= 100) {
    csv += '✓ Good Donation Performance\n';
  } else {
    csv += '• Donation Performance Needs Attention\n';
  }
  
  if (totalMembers >= 100) {
    csv += '✓ Active Member Participation\n';
  } else {
    csv += '• Growing Member Base\n';
  }
  
  csv += '✓ Stable Financial Standing\n\n';
  csv += separator + '\n';
  csv += 'Recommendations\n\n';
  csv += '• Continue stewardship programs.\n';
  csv += '• Encourage regular weekly donations.\n';
  csv += '• Monitor donation trends monthly.\n';
  csv += '• Recognize active donors and volunteers.\n\n';
  csv += separator + '\n';
  csv += 'Generated by KALOOB Donation Management System\n';
  csv += 'This is a computer-generated report.\n';
  csv += separator + '\n';
  
  return csv;
}

export function downloadCSV(filename: string, csv: string) {
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  window.URL.revokeObjectURL(url);
}

export async function downloadPDF(filename: string, element: HTMLElement) {
  try {
    const { jsPDF } = await import('jspdf');
    const html2canvasModule = await import('html2canvas');
    const html2canvas = (html2canvasModule as any).default ?? html2canvasModule;

    const canvas = await html2canvas(element, {
      scale: 2,
      backgroundColor: '#faf7f2',
      useCORS: true,
    });

    const imgData = canvas.toDataURL('image/png');
    const doc = new jsPDF({ unit: 'pt', format: 'a4' }) as any;
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const imgWidth = canvas.width;
    const imgHeight = canvas.height;
    const ratio = Math.min(pageWidth / imgWidth, pageHeight / imgHeight);
    const renderedWidth = imgWidth * ratio;
    const renderedHeight = imgHeight * ratio;
    const x = (pageWidth - renderedWidth) / 2;
    const y = (pageHeight - renderedHeight) / 2;

    doc.addImage(imgData, 'PNG', x, y, renderedWidth, renderedHeight);
    doc.save(filename);
  } catch (err) {
    console.error('PDF generation failed:', err);
    alert('PDF export failed. Please try again.');
  }
}

export async function downloadExcel(filename: string, data: ReportData) {
  try {
    const XLSX = await import('xlsx');
    const separator = '-------------------------------------------------------------';
    const now = new Date().toLocaleString('en-PH');

    const sections = [
      [separator],
      ['KALOOB'],
      ['AUTOMATED TREND ANALYSIS REPORT'],
      [separator],
      ['Chapel', data.chapel.name],
      ['Generated', now],
      [''],
      ['Executive Summary'],
      ...(data.executiveSummary ?? ['Automated summary unavailable.']).map((line) => [line]),
      [''],
      ['Statistical Summary'],
      ...(data.statisticalSummary ?? []).map((line) => [line]),
      [''],
      ['Trend Analysis'],
      ...(data.trendAnalysis ?? []).map((line) => [line]),
      [''],
      ['Interpretation of Results'],
      ...(data.interpretationBullets ?? [data.interpretation]).map((line) => [line]),
      [''],
      ['Recommendations'],
      ...(data.recommendations ?? []).map((line) => [line]),
      [''],
      ['Generated by KALOOB Donation Management System'],
    ];

    const ws = XLSX.utils.aoa_to_sheet(sections);
    ws['!cols'] = [{ wch: 80 }];

    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Report');
    XLSX.writeFile(wb, filename);
  } catch (err) {
    console.error('Excel generation failed. Please install xlsx.', err);
    alert('Excel export requires xlsx library. Using CSV instead.');
  }
}
